name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pakyus_commerce_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Check and create config.json
        run: |
          if [ ! -f config.json ]; then
            echo "config.json not found, creating default config..."
            cat > config.json << EOF
          {
            "app": {
              "name": "Pakyus Commerce",
              "port": 3000,
              "env": "testing"
            },
            "database": {
              "driver": "postgres",
              "host": "localhost",
              "port": 5432,
              "username": "postgres",
              "password": "postgres",
              "name": "pakyus_commerce_test"
            },
            "jwt": {
              "secret": "test-secret-key"
            }
          }
          EOF
          fi

      - name: Run database migrations
        run: |
          migrate -path db/migrations -database "postgres://postgres:postgres@localhost:5432/pakyus_commerce_test?sslmode=disable" up

      - name: Run tests
        run: |
          go test -v ./test/...

      - name: Build application
        run: |
          go build -o pakyus_commerce cmd/web/main.go
